[server]
headless = true
address = "0.0.0.0"
port = 5001

[browser]
gatherUsageStats = false

[watcher]
# Ignore __pycache__ and any .pyc temp files
ignore_directories = ["__pycache__"]
ignore_file_patterns = ["*.pyc*", "*.pyo"]